### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by adityasharat** [flipkart-incubator/android-studio-proteus-plugin#1]
Logs

```
com/android/tools/idea/rendering/AppResourceRepository
java.lang.NoClassDefFoundError: com/android/tools/idea/rendering/AppResourceRepository
	at action.ConvertToJsonAction.getAppResources(ConvertToJsonAction.java:306)
	at action.ConvertToJsonAction.actionPerformed(ConvertToJsonAction.java:81)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:191)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.android.tools.idea.rendering.AppResourceRepository PluginClassLoader[com.flipkart.layoutengine, 1.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more

```

referenced from proteus issue [#60](https://github.com/flipkart-incubator/proteus/issues/60)

**Comment by rajatsharma16** [comment]
Hi
any luck here? Same issue as soon as I updated studio [current version 2.2.2]. Logged here as well
https://youtrack.jetbrains.com/issue/IJSDK-216

**Comment by adityasharat** [comment]
@rajatsharma16 Got the plugin to working with `Android Studios 2.2.3`. Recompiled it using the `master` branch of IDEA community source instead of `145`. Will publish the plugin soon.

**Comment by rajatsharma16** [comment]
@adityasharat thanks. Worked for me after downloading this version.

They have moved the classes to a new package which can now be found in _/Applications/IntelliJ IDEA CE.app/Contents/plugins/android/lib/android.jar_
IntelliJ IDEA 2016.3.1
Build #IC-163.9166.29, built on December 9, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Can you please point me to master. Let me know your opinion on the above solution as well.

**Comment by rajatsharma16** [comment]
worked for me. details here
https://youtrack.jetbrains.com/issue/IJSDK-216

**Comment by adityasharat** [comment]
@rajatsharma16 yes pretty much how it got working. Published new plugin to master [here](https://github.com/flipkart-incubator/android-studio-proteus-plugin/raw/master/proteus-plugin/proteus-plugin.zip)
